using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Profiler.TorchUtils
{
    /// <summary>
    /// Generate awaitable objects that complete whenever a tick is registered.
    /// </summary>
    public sealed class TickTaskSource
    {
        readonly List<TickTask> _incompleteTasks;

        /// <summary>
        /// Instantiate.
        /// </summary>
        public TickTaskSource()
        {
            _incompleteTasks = new List<TickTask>();
        }

        /// <summary>
        /// Generate an awaitable object that completes when Tick() is called.
        /// </summary>
        /// <returns>Awaitable object that completes when Tick() is called.</returns>
        public TickTask GetTask()
        {
            var task = new TickTask();
            _incompleteTasks.Add(task);
            return task;
        }

        /// <summary>
        /// Register a tick.
        /// </summary>
        /// <remarks>All TickTask instances generated by this instance will complete as soon as this method is called.</remarks>
        /// <param name="tick">Frame count of this tick.</param>
        public void Tick(ulong tick)
        {
            foreach (var incompleteTask in _incompleteTasks)
            {
                incompleteTask.CompleteWithTick(tick);
            }

            _incompleteTasks.Clear();
        }

        /// <summary>
        /// Awaitable class that completes when a tick is registered.
        /// </summary>
        public class TickTask : INotifyCompletion
        {
            ulong _result;
            Action _continuation;

            public TickTask GetAwaiter() => this;
            public bool IsCompleted { get; private set; }
            public ulong GetResult() => _result;

            public void OnCompleted(Action continuation)
            {
                if (_continuation != null)
                {
                    throw new Exception("Cannot await twice");
                }

                _continuation = continuation;
            }

            internal void CompleteWithTick(ulong value)
            {
                if (IsCompleted) return;

                _result = value;
                IsCompleted = true;
                _continuation?.Invoke();
            }
        }
    }
}